version: '3.8'

services:
  # Astron-Agent Services
  astron-agent:
    build: .
    ports:
      - "8000:8000"
    environment:
      - RPA_OPENAPI_URL=http://astron-rpa-openapi:8020
      - RPA_MCP_ENDPOINT=http://astron-rpa-openapi:8020/mcp
      - MYSQL_URL=mysql://root:${MYSQL_ROOT_PASSWORD:-root123}@mysql:3306/astron_unified
      - REDIS_URL=redis://redis-cluster:6379
      - RPA_INTEGRATION_ENABLED=true
      - RPA_DEBUG_MODE=${RPA_DEBUG_MODE:-false}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    depends_on:
      - astron-rpa-openapi
      - mysql
      - redis-cluster
    networks:
      - astron-network
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Astron-RPA Services
  astron-rpa-openapi:
    image: astron-rpa-openapi:latest
    ports:
      - "${RPA_OPENAPI_PORT:-8020}:8020"
    environment:
      - AGENT_CALLBACK_URL=http://astron-agent:8000/webhook
      - RPA_ENGINE_URL=http://astron-rpa-engine:8021
      - MYSQL_URL=mysql://root:${MYSQL_ROOT_PASSWORD:-root123}@mysql:3306/rpa
      - REDIS_URL=redis://redis-cluster:6379
      - PYTHON_VERSION=3.13+
      - MCP_ENABLED=true
    depends_on:
      - astron-rpa-engine
      - mysql
      - redis-cluster
    networks:
      - astron-network
    volumes:
      - ./rpa-logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8020/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  astron-rpa-engine:
    image: astron-rpa-engine:latest
    ports:
      - "${RPA_ENGINE_PORT:-8021}:8021"
    environment:
      - PYTHON_VERSION=3.13+
      - COMPONENT_PATH=/app/components
      - MYSQL_URL=mysql://root:${MYSQL_ROOT_PASSWORD:-root123}@mysql:3306/rpa
      - REDIS_URL=redis://redis-cluster:6379
    networks:
      - astron-network
    volumes:
      - ./rpa-components:/app/components
      - ./rpa-workflows:/app/workflows
      - ./rpa-logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8021/health')"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Shared Infrastructure
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root123}
      MYSQL_DATABASE: astron_unified
      MYSQL_USER: ${MYSQL_USER:-astron}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-astron123}
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./integration/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./integration/seed-data.sql:/docker-entrypoint-initdb.d/02-seed-data.sql
    networks:
      - astron-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis-cluster:
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"
    command: redis-server --cluster-enabled yes --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - astron-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: Monitoring Stack
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "${PROMETHEUS_PORT:-9090}:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - astron-network
    restart: unless-stopped
    profiles:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    ports:
      - "${GRAFANA_PORT:-3000}:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin123}
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
    networks:
      - astron-network
    restart: unless-stopped
    profiles:
      - monitoring

  # Optional: Web UI for Management
  astron-web-ui:
    image: astron-web-ui:latest
    ports:
      - "${WEB_UI_PORT:-3001}:3000"
    environment:
      - REACT_APP_AGENT_API_URL=http://localhost:8000
      - REACT_APP_RPA_API_URL=http://localhost:8020
    networks:
      - astron-network
    restart: unless-stopped
    profiles:
      - ui

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

networks:
  astron-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
